CREATE TABLE PRICE
        (
        ID NUMBER(10) NOT NULL,
        BRAND_ID NUMBER(10) NOT NULL,
        START_DATE TIMESTAMP NOT NULL,
        END_DATE TIMESTAMP NOT NULL,
        PRICE_LIST NUMBER(2) NOT NULL,
        PRODUCT_ID NUMBER(10) NOT NULL,
        PRIORITY NUMBER(2) NOT NULL,
        PRICE DECIMAL(20, 2) NOT NULL,
        CURR CHAR(3) NOT NULL,
        PRIMARY KEY(ID)
        );